name = "MinePererecos"
author = "Os admins do servidor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88fc1b5aaab584d2f349edebe553acdf3565a8e4906ed708878bb340a27e900b"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
