name = "MinePererecos"
author = "Os admins do servidor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a56f2891ecae584e7f13770c15af0acbec3231495a327d72ffdc64719225cd9a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
