name = "MinePererecos"
author = "Os admins do servidor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e64cfed383bb21f0a3bcbad04364498e88870068c6329d9c797f551894d1a54b"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
